version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" # on the first of every month
      time: "18:00"
      timezone: "Europe/Berlin"
    assignees:
      - clowa

  #########################################
  # Terraform
  - package-ecosystem: "terraform"
    directory: "/core"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Europe/Berlin"
    assignees:
      - clowa

  - package-ecosystem: "terraform"
    directory: "/prod"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Europe/Berlin"
    assignees:
      - clowa
